export const SET_YEAR = "SET_YEAR";
export const SET_MONTH = "SET_MONTH";
export const SET_DAY = "SET_DAY";

export const TOGGLE_NOTIFICATION_DIALOG = "TOGGLE_NOTIFICATION_DIALOG";
export const CREATE_NOTIFICATION = "CREATE_NOTIFICATION";
export const REMOVE_NOTIFICATION = "REMOVE_NOTIFICATION";

export const PICK_YEAR = "PICK_YEAR";
export const PICK_MONTH = "PICK_MONTH";
export const PICK_DAY = "PICK_DAY";

export const TOGGLE_NEW_TASK_DIALOG = "TOGGLE_NEW_TASK_DIALOG";
export const TOGGLE_TASK_STATUS = "TOGGLE_TASK_STATUS";
export const CREATE_TASK = "CREATE_TASK";
export const REMOVE_TASK = "REMOVE_TASK";
